### ISSUE TITLE
Tunnel association

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/drafts#10]
https://github.com/tsaad-dev/drafts/blob/475a8f9c7341b86f2969824b5df98fffd9b8d53a/te/draft-ietf-teas-yang-te.txt#L657-L660

My understanding was that the associations defined under the tunnel apply to all the paths within the tunnel

Proposed new text:

```
   association-objects:

      A YANG container that holds the set of associations that apply to all the paths of the TE
      tunnel.
```

**Comment by tsaad-dev** [comment]
associations at the tunnel level will associate all paths of a TE tunnel. The tunnel associations can be overridden by the associations configured directly under the TE tunnel path.
