### ISSUE TITLE
Improve clarity of the tunnel hierarchy description

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/drafts#12]
https://github.com/tsaad-dev/drafts/blob/475a8f9c7341b86f2969824b5df98fffd9b8d53a/te/draft-ietf-teas-yang-te.txt#L700-L737

Few proposed text changes to better clarify that:
- the dependency tunnels are tunnels in the server layer of this TE tunnel that could be used if selected by multi-layer path computation;
- the hierarchical-link is the link in the client layer supported by this TE tunnel

```
   hierarchy:

      A YANG container that holds hierarchy related properties of the TE
      tunnel (see Figure 5).  A TE LSP can be set up in MPLS or
      Generalized MPLS (GMPLS) networks to be used as a TE links to
      carry traffic in other (client) networks [RFC6107].  In this case,
      the model introduces the TE tunnel hierarchical link endpoint
      parameters to identify the specific link in the client layer that
      the underlying TE tunnel is associated with.  The hierarchy
      container includes the following:

         +  dependency-tunnels: a hierarchical TE tunnel provisioned or
            to be provisioned in an immediately adjacent server layer
            this TE tunnel depends on for multi-layer path
            computation.  A dependency TE tunnel is provisioned if and
            only if it is used (selected by path computation) at least
            by one client layer TE tunnel.  The TE link in the client
            layer network topology supported by a dependency TE tunnel is
            dynamically created only when the dependency TE tunnel is
            actually provisioned.

         +  hierarchical-link: A YANG container that holds the identity
            of the hierarchical link (in client layer) that is supported by 
            this TE tunnel.  A hierarchical-link is by a node hosting
            the link and its source and destination link termination
            point identifiers.
```

**Comment by tsaad-dev** [comment]
OLD:
         +  dependency-tunnels: a hierarchical TE tunnel provisioned or
            to be provisioned in an immediately adjacent server layer
NEW:
         +  dependency-tunnels: A set of hierarchical TE tunnels provisioned or
            to be provisioned in the immediate lower layer that this TE tunnel depends on
           for multi-layer path computation. 

OLD:
         +  hierarchical-link: A YANG container that holds the identity
            of the hierarchical link (in client layer) that is supported by 
            this TE tunnel.  A hierarchical-link is by a node hosting
            the link and its source and destination link termination
            point identifiers.

NEW:

         +  hierarchical-link: A YANG container that holds the identity
            of the hierarchical link (in the client layer) that is supported by 
            this TE tunnel.  The endpoints of a hierarchical-link are defined by TE tunnel
            source and destination endpoints. The hierarchical link can be identified by its
            source and destination link termination point identifiers.
