### ISSUE TITLE
Named path constraints

### ISSUE THREAD

**Issue by sergiobelotti** [tsaad-dev/drafts#14]
https://github.com/tsaad-dev/drafts/blob/475a8f9c7341b86f2969824b5df98fffd9b8d53a/te/draft-ietf-teas-yang-te.txt#L489

In the definition I think is missing the important point that "named" constraints area set of constraints that can be "referenced" by several tunnels. This is a concept , trivial in packet network, but not in optical.
So in the definition I would just add : "Each named constraints is composed of a set of constraints that can be referenced by several tunnels and applied during path computation........"

**Comment by tsaad-dev** [comment]
Addressed in issue #5
