### ISSUE TITLE
TE tunnel definitions

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/drafts#6]
https://github.com/tsaad-dev/drafts/blob/475a8f9c7341b86f2969824b5df98fffd9b8d53a/te/draft-ietf-teas-yang-te.txt#L537-L553

Few comments:
- Not all the LSPs within a tunnel do need to be between the source and destination TTPs
- I think that the connection-oriented services is the TE tunnel and not the TE tunnel LSP
- I think we can simplify a bit the TE tunnel segment definition
- I am wondering whether the TE tunnel hand-off is the point where a path enters/exits rather than the TE tunnel enters/exits

Proposed text change:

```
   TE tunnel:

      A a connection-oriented service provided by a network layer
      for the delivery of client data between source and
      destination TE tunnel termination points.
      A TE tunnel contains one or more LSPs.

   TE Tunnel Segment:

      A part of a multi-domain TE tunnel that
      spans a given network domain.

   TE Tunnel Hand-off:

      An access link or inter-domain link by which a path of a multi-domain TE
      tunnel enters or exits a given network domain.

```
Regarding the TE tunnel hand-off, there is also a comment from Sergio on the TNBI draft which is also applicable to this definition and requires further discussion:
https://mailarchive.ietf.org/arch/msg/ccamp/O1fNkfgZljBppiekwpcHj7P2a3s/

Note - this text changes are addressing https://github.com/tsaad-dev/te/issues/59

**Comment by tsaad-dev** [comment]
TE Tunnel Segment:

      A part of a multi-domain TE tunnel that is within a specific network domain.

**Comment by tsaad-dev** [comment]
TE Tunnel Hand-off:

      An inter-domain link on which the path of a multi-domain TE
      tunnel enters or exits a given network domain.

**Comment by tsaad-dev** [comment]
Addressed
