### ISSUE TITLE
Tunnel name uniqueness

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/drafts#7]
https://github.com/tsaad-dev/drafts/blob/475a8f9c7341b86f2969824b5df98fffd9b8d53a/te/draft-ietf-teas-yang-te.txt#L607-L612

I am not sure the term "canonical form" is clear in the context of tunnel name. What about the text in https://github.com/tsaad-dev/te/issues/50#issuecomment-629666746?

Moreover, the need to ensure unique names applies also within a controllers' hierarchy.

Proposed updated text:

```
   name:

      A YANG leaf that holds the name of a tunnel.  The name of the
      tunnel uniquely identifies a tunnel within the list.  The name of
      the tunnel can be formatted as an URI containing both the namespace and the name
      (which is uniquely assigned within the namespace) to ensure
      uniqueness of tunnels present on multiple devices or controllers.

```

**Comment by tsaad-dev** [comment]
name:

      A YANG leaf that holds the name of a tunnel.  The name of the
      tunnel uniquely identifies a tunnel within the TE tunnel list.  The name of
      the tunnel can be formatted as a URI (including the namespace)
      to ensure uniqueness amongst the TE tunnels present on devices and controllers.
