### ISSUE TITLE
Source and Destination TTPs

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/drafts#8]
https://github.com/tsaad-dev/drafts/blob/475a8f9c7341b86f2969824b5df98fffd9b8d53a/te/draft-ietf-teas-yang-te.txt#L636-L643

My understanding is that the source and destination TTPs are identified by the (node-id, tunnel-tp-id) pair since the tunnel-tp-id is unique in the scope of the node.

I guess that the tunnel-tp-id can be omitted in case the node has only one TTP.

Proposed new text:

```
   source/destination:

      The identifier of the nodes where the TE tunnel source and destination TTPs are located.

   src-tunnel-tp-id/dst-tunnel-tp-id:

      The identifier of souce and destination TTPs within the source and destination nodes. It can be omitted if the source or 
      destination node have only one TTP.

```      

In alternative, defining a source and a destination container would be more intuitive from a YANG perspective.

**Comment by tsaad-dev** [comment]
OLD:
source/destination: YANG leafs that define the tunnel source and destination node endpoints. 


src-tunnel-tp-id/dst-tunnel-tp-id:   YANG leafs that define the tunnel termination point identifiers. 



NEW:

    source/destination: YANG leafs that define the tunnel source and destination node endpoints. 

   src-tunnel-tp-id/dst-tunnel-tp-id:

      The identifiers of source and destination TE tunnel termination points (TTPs) [RFC8795] residing on the source and destination \ nodes. TTP identifiers are optional on nodes that have a single TTP per node. For example, TTP identifiers are optional for packet (IP/MPLS) routers.
